numero = int(input('Digite um número: '))
print('Tabuada do {}:'.format(numero))
print(' {} x  1 = {:2}'.format(numero,numero*1))
print(' {} x  2 = {:2}'.format(numero,numero*2))
print(' {} x  3 = {:2}'.format(numero,numero*3))
print(' {} x  4 = {:2}'.format(numero,numero*4))
print(' {} x  5 = {:2}'.format(numero,numero*5))
print(' {} x  6 = {:2}'.format(numero,numero*6))
print(' {} x  7 = {:2}'.format(numero,numero*7))
print(' {} x  8 = {:2}'.format(numero,numero*8))
print(' {} x  9 = {:2}'.format(numero,numero*9))
print(' {} x 10 = {:2}'.format(numero,numero*10))