termos = int(input('Digite o número de termos da sequência:'))
t1 = 0
t2 = 1
n = 3
print('{} - {} '.format(t1, t2), end='')
while n <= termos:
    t3 = t1 + t2
    print('- {} '.format(t3), end='')
    t1 = t2
    t2 = t3
    n += 1
